In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
sp500 = pd.read_csv("^GSPC_2000~2018.csv")
sp500.index = sp500.Date.map(lambda x : pd.Timestamp(x))
del sp500['Date']
del sp500['Adj Close']
sp500.Volume = sp500.Volume / 1e9

In [3]:
sp500["pct_change"] = sp500.Close.pct_change()
for i in range(3, 31, 2):
    sp500["close_ma_{}".format(i)] = \
      sp500.Close.rolling(window = i).mean()
for i in [7, 21, 30, 60, 90, 91, 100, 120]:
    sp500["his_vol_{}".format(i)] = \
      sp500["pct_change"].rolling(window = i).std()*(252**0.5)
for i in [1, 3, 5, 7, 10, 12, 14]:
    sp500['returnsCC{}'.format(i)] = \
      np.log(sp500.Close / sp500.Close.shift(i))
    sp500['returnsOO{}'.format(i)] = \
      np.log(sp500.Open / sp500.Open.shift(i))
    sp500['returnsCO{}'.format(i)] = \
      np.log(sp500.Open / sp500.Close.shift(i))
    sp500['returnsOC{}'.format(i)] = \
      np.log(sp500.Close / sp500.Open.shift(i))
for i in [1, 3, 5, 7, 10, 15, 20, 25, 30, 35, 40, 45, 50,
          55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120]:
    for shift in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
        sp500['Y1_{}_s{}'.format(i, shift)] = (sp500.Close - sp500.Close.shift(shift).rolling(i).mean())
        sp500['Y3_{}_s{}'.format(i, shift)] = (sp500.Close.rolling(i).mean() - sp500.Close.shift(shift).rolling(i).mean())
        sp500['sh{}_Y1_{}'.format(shift, i)] = (sp500['Y1_{}_s{}'.format(i, shift)]).shift(-1*shift)
        sp500['sh{}_Y3_{}'.format(shift, i)] = (sp500['Y3_{}_s{}'.format(i, shift)]).shift(-1*shift)
        sp500['sh{}_Y_val'.format(shift)] = (sp500.Close - sp500.Close.shift(shift)).shift(-1*shift)

In [4]:
train = sp500.loc['2005-01-01':'2016-01-01']
test = sp500.loc['2016-01-01':]

In [5]:
train.head()

,Open,High,Low,Close,Volume,pct_change,close_ma_3,close_ma_5,close_ma_7,close_ma_9,...,sh8_Y1_120,sh8_Y3_120,Y1_120_s9,Y3_120_s9,sh9_Y1_120,sh9_Y3_120,Y1_120_s10,Y3_120_s10,sh10_Y1_120,sh10_Y3_120
Date,,,,,,,,,,,,,,,,,,,,,
2005-01-03,1211.920044,1217.800049,1200.319946,1202.079956,1.5108,-0.008119,1209.183350,1210.908008,1209.941441,1209.401109,...,42.364950,5.880167,73.935540,6.940584,49.435019,6.627584,74.383957,7.389001,60.894979,7.465583
2005-01-04,1202.079956,1205.839966,1185.390015,1188.050049,1.7210,-0.011671,1200.683350,1205.810010,1206.787162,1207.467787,...,48.757018,5.949583,59.268049,6.981002,60.216978,6.787582,59.905633,7.618585,48.867003,7.489249
2005-01-05,1188.050049,1192.729980,1183.719971,1183.739990,1.7389,-0.003628,1191.289998,1199.868018,1203.761440,1204.597792,...,59.530729,6.101333,54.256407,6.965669,48.180754,6.802999,54.957990,7.667252,38.960783,7.417083
2005-01-06,1183.739990,1191.630005,1183.270020,1187.890015,1.5691,0.003506,1186.560018,1194.736011,1200.097151,1202.126682,...,47.455837,6.078082,57.623765,6.907918,38.235866,6.692166,58.406432,7.690585,30.695827,7.202583
2005-01-07,1187.890015,1192.199951,1182.160034,1186.189941,1.4779,-0.001431,1185.939982,1189.589990,1196.202863,1200.045559,...,37.589867,6.046167,55.202107,6.832333,30.049828,6.556584,55.923691,7.553917,25.929833,7.090417

In [6]:
test.head()

,Open,High,Low,Close,Volume,pct_change,close_ma_3,close_ma_5,close_ma_7,close_ma_9,...,sh8_Y1_120,sh8_Y3_120,Y1_120_s9,Y3_120_s9,sh9_Y1_120,sh9_Y3_120,Y1_120_s10,Y3_120_s10,sh10_Y1_120,sh10_Y3_120
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,2038.199951,2038.199951,1989.680054,2012.660034,4.30488,-0.015304,2039.986694,2050.964038,2054.300031,2048.913357,...,-114.943035,-11.293412,-26.183301,-2.060334,-156.453045,-12.854328,-26.662968,-2.540001,-155.453045,-14.620329
2016-01-05,2013.780029,2021.939941,2004.170044,2016.709961,3.70662,0.002012,2024.436645,2043.006030,2047.502877,2048.420017,...,-155.697295,-12.098579,-21.664458,-2.347168,-154.697295,-13.864579,-22.133374,-2.816084,-176.697295,-15.941580
2016-01-06,2011.709961,2011.709961,1979.050049,1990.260010,4.33666,-0.013115,2006.543335,2025.386011,2037.398594,2043.007799,...,-153.580378,-12.747662,-47.799325,-3.149001,-175.580378,-14.824663,-48.114409,-3.464085,-165.920344,-16.821662
2016-01-07,1985.319946,1985.319946,1938.829956,1943.089966,5.07659,-0.023700,1983.353312,2001.331982,2021.197161,2029.541124,...,-174.050796,-13.295081,-94.932120,-4.641334,-164.390762,-15.292080,-94.969369,-4.678584,-126.480728,-16.933247
2016-01-08,1945.969971,1960.400024,1918.459961,1922.030029,4.66494,-0.010838,1951.793335,1976.950000,1998.864293,2014.101128,...,-162.672012,-13.573330,-115.822472,-6.190500,-124.761978,-15.214497,-115.992057,-6.360084,-154.582046,-17.055831

In [15]:
X = [i for i in sp500.columns 
     if (i.find('sh') == -1)
     if (i.find('Y') == -1)]

In [23]:
y_val = [i for i in [i for i in train.columns if i not in X] if i.find('val') != -1]
y_li = [i for i in [i for i in [i for i in train.columns if i not in X] if i.find('val') == -1] if i.find('sh') != -1]

In [29]:
scale_X = [i for i in X if (i.find('Open') != -1) |
                 (i.find('Close') != -1) |
                 (i.find('Low') != -1) |
                 (i.find('High') != -1) |
                 (i.find('close') != -1)]

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, Lasso
lr = LinearRegression()
rid = Ridge()
las = Lasso()
from xgboost import XGBRegressor
xgb = XGBRegressor()

In [69]:
from sklearn import metrics

def modelfit(alg, train, test, X, y):
    train_data = train[X]
    test_data = test[X]
    train_label = train[y]
    test_label = test[y]
    try:
        k = int(y[2:4])
    except:
        k = int(y[2])
    real_y = 'sh{}_Y_val'.format(k)
    real_label = test[real_y]
#     td = train_data[scale_X].values
#     smoothing_window_size = 600
#     for di in range(0, 2400, smoothing_window_size):
#         minmax.fit(td[di:di+smoothing_window_size,:])
#         td[di:di+smoothing_window_size,:] = minmax.transform(td[di:di+smoothing_window_size,:])
#     minmax.fit(td[di+smoothing_window_size:, :])
#     td[di+smoothing_window_size:,:] = minmax.transform(td[di+smoothing_window_size:,:])
#     test_d = minmax.transform(test_data[scale_X].values)
#     train_data.loc[:,scale_X] = td
#     test_data.loc[:,scale_X] = test_d
    alg.fit(train_data, train_label)
    pred = alg.predict(test_data)
    pred_class = np.where(pred>0, 1, 0)
    real_class = np.where(real_label.T>0, 1 , 0)
    acc = metrics.accuracy_score(real_class, pred_class)
    auc = metrics.roc_auc_score(real_class, pred_class)
    return acc, auc

In [70]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

In [71]:
%run moon_code

In [72]:
sp500_ = sp500.loc['2013-07-01':]
train, test = train_test_split(sp500_, 0.8, dtrain=True)

In [77]:
X = [i for i in sp500.columns 
     if (i.find('sh') == -1)
     if (i.find('Y') == -1)]

In [78]:
xgb = XGBRegressor()
import time
start = time.time()
acc, auc = modelfit(xgb, train, test, X, 'sh1_Y3_7')
elapse = time.time() - start

In [85]:
for y in y_li:
    acc, auc = modelfit(xgb, train, test, X, y)
    print(y, '\t{:.4f}, {:.4f}'.format(acc, auc))

sh1_Y1_1 	0.5438, 0.5424
sh1_Y3_1 	0.5438, 0.5424
sh2_Y1_1 	0.5146, 0.5104
sh2_Y3_1 	0.5146, 0.5104
sh3_Y1_1 	0.4380, 0.4259
sh3_Y3_1 	0.4380, 0.4259
sh4_Y1_1 	0.4891, 0.4559
sh4_Y3_1 	0.4891, 0.4559
sh5_Y1_1 	0.4891, 0.4412
sh5_Y3_1 	0.4891, 0.4412
sh6_Y1_1 	0.5109, 0.4770
sh6_Y3_1 	0.5109, 0.4770
sh7_Y1_1 	0.5328, 0.4870
sh7_Y3_1 	0.5328, 0.4870
sh8_Y1_1 	0.5255, 0.4721
sh8_Y3_1 	0.5255, 0.4721
sh9_Y1_1 	0.5219, 0.4579
sh9_Y3_1 	0.5219, 0.4579
sh10_Y1_1 	0.6022, 0.4891
sh10_Y3_1 	0.6022, 0.4891
sh1_Y1_3 	0.4891, 0.4882
sh1_Y3_3 	0.5073, 0.5071
sh2_Y1_3 	0.5146, 0.5127
sh2_Y3_3 	0.5000, 0.4931
sh3_Y1_3 	0.4891, 0.4785
sh3_Y3_3 	0.5000, 0.4901
sh4_Y1_3 	0.4854, 0.4404
sh4_Y3_3 	0.4891, 0.4528
sh5_Y1_3 	0.4672, 0.4185
sh5_Y3_3 	0.4599, 0.4152
sh6_Y1_3 	0.4745, 0.4512
sh6_Y3_3 	0.4635, 0.4168
sh7_Y1_3 	0.5000, 0.4521
sh7_Y3_3 	0.4854, 0.4579
sh8_Y1_3 	0.5401, 0.4666
sh8_Y3_3 	0.5146, 0.4632
sh9_Y1_3 	0.5182, 0.4382
sh9_Y3_3 	0.5000, 0.4253
sh10_Y1_3 	0.6277, 0.4954
sh10_Y3_3 	0.5657, 0.4652
sh1_Y1_5 	0.5036, 0.5032
sh1_Y3_5 	0.5219, 0.5171
sh2_Y1_5 	0.5255, 0.5107
sh2_Y3_5 	0.5292, 0.5150
sh3_Y1_5 	0.4964, 0.4877
sh3_Y3_5 	0.5365, 0.5314
sh4_Y1_5 	0.5219, 0.4878
sh4_Y3_5 	0.5365, 0.5062
sh5_Y1_5 	0.4854, 0.4353
sh5_Y3_5 	0.5146, 0.4828
sh6_Y1_5 	0.4854, 0.4289
sh6_Y3_5 	0.4781, 0.4359
sh7_Y1_5 	0.5000, 0.4312
sh7_Y3_5 	0.4818, 0.4399
sh8_Y1_5 	0.5182, 0.4400
sh8_Y3_5 	0.4927, 0.4383
sh9_Y1_5 	0.5730, 0.4842
sh9_Y3_5 	0.5255, 0.4515
sh10_Y1_5 	0.5584, 0.4527
sh10_Y3_5 	0.5584, 0.4550
sh1_Y1_7 	0.5073, 0.5016
sh1_Y3_7 	0.4745, 0.4692
sh2_Y1_7 	0.5000, 0.4863
sh2_Y3_7 	0.5219, 0.5064
sh3_Y1_7 	0.4818, 0.4789
sh3_Y3_7 	0.5000, 0.4866
sh4_Y1_7 	0.5511, 0.4825
sh4_Y3_7 	0.5073, 0.4773
sh5_Y1_7 	0.5219, 0.4501
sh5_Y3_7 	0.5109, 0.4726
sh6_Y1_7 	0.4964, 0.4527
sh6_Y3_7 	0.5255, 0.4775
sh7_Y1_7 	0.5328, 0.4631
sh7_Y3_7 	0.5182, 0.4389
sh8_Y1_7 	0.5730, 0.4812
sh8_Y3_7 	0.5182, 0.4505
sh9_Y1_7 	0.5839, 0.4837
sh9_Y3_7 	0.5328, 0.4779
sh10_Y1_7 	0.5803, 0.4630
sh10_Y3_7 	0.5547, 0.4409
sh1_Y1_10 	0.4854, 0.4800
sh1_Y3_10 	0.4599, 0.4507
sh2_Y1_10 	0.5109, 0.4923
sh2_Y3_10 	0.5109, 0.4912
sh3_Y1_10 	0.5036, 0.4830
sh3_Y3_10 	0.4854, 0.4709
sh4_Y1_10 	0.5219, 0.4723
sh4_Y3_10 	0.4635, 0.4393
sh5_Y1_10 	0.5000, 0.4432
sh5_Y3_10 	0.4891, 0.4628
sh6_Y1_10 	0.5219, 0.4718
sh6_Y3_10 	0.5109, 0.4783
sh7_Y1_10 	0.5474, 0.4932
sh7_Y3_10 	0.5219, 0.4704
sh8_Y1_10 	0.6022, 0.4998
sh8_Y3_10 	0.4781, 0.4299
sh9_Y1_10 	0.6022, 0.4890
sh9_Y3_10 	0.5182, 0.4568
sh10_Y1_10 	0.6350, 0.5034
sh10_Y3_10 	0.5511, 0.4471
sh1_Y1_15 	0.4672, 0.4581
sh1_Y3_15 	0.4635, 0.4542
sh2_Y1_15 	0.4854, 0.4713
sh2_Y3_15 	0.5109, 0.4843
sh3_Y1_15 	0.5109, 0.4860
sh3_Y3_15 	0.4745, 0.4551
sh4_Y1_15 	0.4927, 0.4402
sh4_Y3_15 	0.4489, 0.4101
sh5_Y1_15 	0.4891, 0.4355
sh5_Y3_15 	0.4526, 0.4149
sh6_Y1_15 	0.4964, 0.4646
sh6_Y3_15 	0.4854, 0.4473
sh7_Y1_15 	0.5657, 0.5025
sh7_Y3_15 	0.5182, 0.4703
sh8_Y1_15 	0.6022, 0.5015
sh8_Y3_15 	0.5328, 0.4798
sh9_Y1_15 	0.6277, 0.5189
sh9_Y3_15 	0.5438, 0.4868
sh10_Y1_15 	0.6423, 0.5158
sh10_Y3_15 	0.6022, 0.5298
sh1_Y1_20 	0.4708, 0.4611
sh1_Y3_20 	0.4745, 0.4607
sh2_Y1_20 	0.5219, 0.4961
sh2_Y3_20 	0.5328, 0.4987
sh3_Y1_20 	0.4964, 0.4712
sh3_Y3_20 	0.5219, 0.4941
sh4_Y1_20 	0.4854, 0.4264
sh4_Y3_20 	0.5146, 0.4678
sh5_Y1_20 	0.4891, 0.4340
sh5_Y3_20 	0.5036, 0.4592
sh6_Y1_20 	0.5438, 0.4852
sh6_Y3_20 	0.5328, 0.4917
sh7_Y1_20 	0.5292, 0.4720
sh7_Y3_20 	0.5401, 0.4886
sh8_Y1_20 	0.6095, 0.5162
sh8_Y3_20 	0.5657, 0.5048
sh9_Y1_20 	0.5912, 0.4951
sh9_Y3_20 	0.5876, 0.5202
sh10_Y1_20 	0.6204, 0.5078
sh10_Y3_20 	0.6095, 0.5287
sh1_Y1_25 	0.4964, 0.4852
sh1_Y3_25 	0.4964, 0.4861
sh2_Y1_25 	0.5109, 0.4843
sh2_Y3_25 	0.5511, 0.5214
sh3_Y1_25 	0.4891, 0.4595
sh3_Y3_25 	0.5438, 0.5206
sh4_Y1_25 	0.5109, 0.4523
sh4_Y3_25 	0.5255, 0.4691
sh5_Y1_25 	0.5292, 0.4635
sh5_Y3_25 	0.5219, 0.4717
sh6_Y1_25 	0.5584, 0.4923
sh6_Y3_25 	0.5365, 0.4829
sh7_Y1_25 	0.5693, 0.4966
sh7_Y3_25 	0.5657, 0.5010
sh8_Y1_25 	0.6241, 0.5368
sh8_Y3_25 	0.5912, 0.5222
sh9_Y1_25 	0.6058, 0.5200
sh9_Y3_25 	0.5912, 0.5175
sh10_Y1_25 	0.6168, 0.5140
sh10_Y3_25 	0.6131, 0.5248
sh1_Y1_30 	0.4964, 0.4861
sh1_Y3_30 	0.5219, 0.5102
sh2_Y1_30 	0.5219, 0.4869
sh2_Y3_30 	0.5547, 0.5246
sh3_Y1_30 	0.4927, 0.4619
sh3_Y3_30 	0.5365, 0.5124
sh4_Y1_30 	0.5255, 0.4737
sh4_Y3_30 	0.5547, 0.5120
sh5_Y1_30 	0.5365, 0.4825
sh5_Y3_30 	0.5584, 0.5182
sh6_Y1_30 	0.5547, 0.4932
sh6_Y3_30 	0.5839, 0.5470
sh7_Y1_30 	0.5766, 0.5101
sh7_Y3_30 	0.6058, 0.5660
sh8_Y1_30 	0.6168, 0.5273
sh8_Y3_30 	0.5949, 0.5426
sh9_Y1_30 	0.6022, 0.5189
sh9_Y3_30 	0.6131, 0.5594
sh10_Y1_30 	0.6460, 0.5435
sh10_Y3_30 	0.6423, 0.5814
sh1_Y1_35 	0.5000, 0.4882
sh1_Y3_35 	0.5073, 0.4956
sh2_Y1_35 	0.5146, 0.4817
sh2_Y3_35 	0.5474, 0.5182
sh3_Y1_35 	0.5073, 0.4776
sh3_Y3_35 	0.5255, 0.5017
sh4_Y1_35 	0.5255, 0.4722
sh4_Y3_35 	0.5547, 0.5167
sh5_Y1_35 	0.5036, 0.4420
sh5_Y3_35 	0.5620, 0.5270
sh6_Y1_35 	0.5219, 0.4665
sh6_Y3_35 	0.5876, 0.5567
sh7_Y1_35 	0.5766, 0.5131
sh7_Y3_35 	0.6058, 0.5705
sh8_Y1_35 	0.5839, 0.5006
sh8_Y3_35 	0.6058, 0.5602
sh9_Y1_35 	0.5949, 0.5018
sh9_Y3_35 	0.6022, 0.5488
sh10_Y1_35 	0.6131, 0.5067
sh10_Y3_35 	0.6533, 0.6012
sh1_Y1_40 	0.4927, 0.4822
sh1_Y3_40 	0.5219, 0.5141
sh2_Y1_40 	0.5438, 0.5208
sh2_Y3_40 	0.5730, 0.5530
sh3_Y1_40 	0.5328, 0.5108
sh3_Y3_40 	0.5584, 0.5423
sh4_Y1_40 	0.5474, 0.5090
sh4_Y3_40 	0.5766, 0.5504
sh5_Y1_40 	0.5146, 0.4641
sh5_Y3_40 	0.5766, 0.5522
sh6_Y1_40 	0.5438, 0.4984
sh6_Y3_40 	0.5766, 0.5461
sh7_Y1_40 	0.5657, 0.5100
sh7_Y3_40 	0.5949, 0.5553
sh8_Y1_40 	0.5839, 0.5023
sh8_Y3_40 	0.6058, 0.5567
sh9_Y1_40 	0.5803, 0.4938
sh9_Y3_40 	0.6058, 0.5498
sh10_Y1_40 	0.6168, 0.5231
sh10_Y3_40 	0.6241, 0.5559
sh1_Y1_45 	0.4854, 0.4770
sh1_Y3_45 	0.4708, 0.4602
sh2_Y1_45 	0.5365, 0.5133
sh2_Y3_45 	0.5365, 0.5064
sh3_Y1_45 	0.5438, 0.5224
sh3_Y3_45 	0.5255, 0.5034
sh4_Y1_45 	0.5584, 0.5150
sh4_Y3_45 	0.5474, 0.4997
sh5_Y1_45 	0.5328, 0.4881
sh5_Y3_45 	0.5365, 0.4897
sh6_Y1_45 	0.5547, 0.5116
sh6_Y3_45 	0.5657, 0.5249
sh7_Y1_45 	0.5693, 0.5160
sh7_Y3_45 	0.5912, 0.5463
sh8_Y1_45 	0.5730, 0.5021
sh8_Y3_45 	0.6168, 0.5726
sh9_Y1_45 	0.5766, 0.4890
sh9_Y3_45 	0.6204, 0.5709
sh10_Y1_45 	0.6058, 0.5032
sh10_Y3_45 	0.6533, 0.6035
sh1_Y1_50 	0.4964, 0.4878
sh1_Y3_50 	0.4927, 0.4831
sh2_Y1_50 	0.5547, 0.5291
sh2_Y3_50 	0.5438, 0.5196
sh3_Y1_50 	0.5401, 0.5200
sh3_Y3_50 	0.5401, 0.5200
sh4_Y1_50 	0.5620, 0.5227
sh4_Y3_50 	0.5547, 0.5151
sh5_Y1_50 	0.5292, 0.4836
sh5_Y3_50 	0.5620, 0.5213
sh6_Y1_50 	0.5547, 0.5116
sh6_Y3_50 	0.5876, 0.5528
sh7_Y1_50 	0.5620, 0.5084
sh7_Y3_50 	0.6022, 0.5629
sh8_Y1_50 	0.5912, 0.5274
sh8_Y3_50 	0.6168, 0.5709
sh9_Y1_50 	0.5657, 0.4839
sh9_Y3_50 	0.6168, 0.5661
sh10_Y1_50 	0.6131, 0.5202
sh10_Y3_50 	0.6606, 0.5979
sh1_Y1_55 	0.5073, 0.4981
sh1_Y3_55 	0.5146, 0.5067
sh2_Y1_55 	0.5657, 0.5432
sh2_Y3_55 	0.5584, 0.5380
sh3_Y1_55 	0.5474, 0.5291
sh3_Y3_55 	0.5365, 0.5184
sh4_Y1_55 	0.5620, 0.5243
sh4_Y3_55 	0.5584, 0.5259
sh5_Y1_55 	0.5438, 0.5045
sh5_Y3_55 	0.5766, 0.5465
sh6_Y1_55 	0.5511, 0.5112
sh6_Y3_55 	0.5657, 0.5368
sh7_Y1_55 	0.5657, 0.5160
sh7_Y3_55 	0.5876, 0.5567
sh8_Y1_55 	0.5584, 0.4850
sh8_Y3_55 	0.5985, 0.5629
sh9_Y1_55 	0.5657, 0.4839
sh9_Y3_55 	0.5912, 0.5530
sh10_Y1_55 	0.6022, 0.5049
sh10_Y3_55 	0.6277, 0.5859
sh1_Y1_60 	0.5146, 0.5046
sh1_Y3_60 	0.5073, 0.4990
sh2_Y1_60 	0.5620, 0.5355
sh2_Y3_60 	0.5620, 0.5423
sh3_Y1_60 	0.5584, 0.5406
sh3_Y3_60 	0.5584, 0.5441
sh4_Y1_60 	0.5620, 0.5212
sh4_Y3_60 	0.5657, 0.5398
sh5_Y1_60 	0.5365, 0.4926
sh5_Y3_60 	0.5839, 0.5626
sh6_Y1_60 	0.5839, 0.5497
sh6_Y3_60 	0.5912, 0.5691
sh7_Y1_60 	0.5876, 0.5447
sh7_Y3_60 	0.6058, 0.5824
sh8_Y1_60 	0.5730, 0.5108
sh8_Y3_60 	0.6058, 0.5759
sh9_Y1_60 	0.5839, 0.5173
sh9_Y3_60 	0.5985, 0.5663
sh10_Y1_60 	0.6204, 0.5440
sh10_Y3_60 	0.6350, 0.5983
sh1_Y1_65 	0.5219, 0.5136
sh1_Y3_65 	0.5109, 0.5024
sh2_Y1_65 	0.5730, 0.5507
sh2_Y3_65 	0.5730, 0.5530
sh3_Y1_65 	0.5401, 0.5191
sh3_Y3_65 	0.5584, 0.5432
sh4_Y1_65 	0.5657, 0.5335
sh4_Y3_65 	0.5766, 0.5520
sh5_Y1_65 	0.5693, 0.5331
sh5_Y3_65 	0.5876, 0.5628
sh6_Y1_65 	0.5985, 0.5674
sh6_Y3_65 	0.5949, 0.5709
sh7_Y1_65 	0.6058, 0.5660
sh7_Y3_65 	0.6168, 0.5931
sh8_Y1_65 	0.5912, 0.5378
sh8_Y3_65 	0.6022, 0.5711
sh9_Y1_65 	0.5803, 0.5162
sh9_Y3_65 	0.6022, 0.5693

sh10_Y1_65 	0.6131, 0.5361
sh10_Y3_65 	0.6387, 0.6034
sh1_Y1_70 	0.5219, 0.5132
sh1_Y3_70 	0.5255, 0.5184
sh2_Y1_70 	0.5803, 0.5616
sh2_Y3_70 	0.5657, 0.5501
sh3_Y1_70 	0.5401, 0.5208
sh3_Y3_70 	0.5547, 0.5417
sh4_Y1_70 	0.5657, 0.5335
sh4_Y3_70 	0.5657, 0.5460
sh5_Y1_70 	0.5584, 0.5211
sh5_Y3_70 	0.5839, 0.5626
sh6_Y1_70 	0.5985, 0.5674
sh6_Y3_70 	0.5985, 0.5792
sh7_Y1_70 	0.6168, 0.5826
sh7_Y3_70 	0.6058, 0.5839
sh8_Y1_70 	0.6058, 0.5585
sh8_Y3_70 	0.6058, 0.5793
sh9_Y1_70 	0.6022, 0.5432
sh9_Y3_70 	0.6022, 0.5730
sh10_Y1_70 	0.6058, 0.5326
sh10_Y3_70 	0.6350, 0.6051
sh1_Y1_75 	0.5255, 0.5171
sh1_Y3_75 	0.5255, 0.5184
sh2_Y1_75 	0.5766, 0.5573
sh2_Y3_75 	0.5766, 0.5584
sh3_Y1_75 	0.5657, 0.5506
sh3_Y3_75 	0.5657, 0.5532
sh4_Y1_75 	0.5657, 0.5351
sh4_Y3_75 	0.5766, 0.5520
sh5_Y1_75 	0.5620, 0.5256
sh5_Y3_75 	0.5876, 0.5657
sh6_Y1_75 	0.5949, 0.5629
sh6_Y3_75 	0.5949, 0.5748
sh7_Y1_75 	0.6131, 0.5795
sh7_Y3_75 	0.6058, 0.5839
sh8_Y1_75 	0.6204, 0.5756
sh8_Y3_75 	0.6131, 0.5888
sh9_Y1_75 	0.6095, 0.5528
sh9_Y3_75 	0.6131, 0.5874
sh10_Y1_75 	0.6168, 0.5479
sh10_Y3_75 	0.6350, 0.6029
sh1_Y1_80 	0.5292, 0.5218
sh1_Y3_80 	0.5255, 0.5162
sh2_Y1_80 	0.5730, 0.5553
sh2_Y3_80 	0.5438, 0.5322
sh3_Y1_80 	0.5620, 0.5473
sh3_Y3_80 	0.5511, 0.5384
sh4_Y1_80 	0.5693, 0.5397
sh4_Y3_80 	0.5693, 0.5443
sh5_Y1_80 	0.5730, 0.5448
sh5_Y3_80 	0.5766, 0.5551
sh6_Y1_80 	0.5912, 0.5598
sh6_Y3_80 	0.5912, 0.5704
sh7_Y1_80 	0.6131, 0.5795
sh7_Y3_80 	0.5912, 0.5657
sh8_Y1_80 	0.6168, 0.5726
sh8_Y3_80 	0.6131, 0.5870
sh9_Y1_80 	0.6204, 0.5728
sh9_Y3_80 	0.6131, 0.5856
sh10_Y1_80 	0.6314, 0.5638
sh10_Y3_80 	0.6533, 0.6193
sh1_Y1_85 	0.5292, 0.5218
sh1_Y3_85 	0.5146, 0.5059
sh2_Y1_85 	0.5730, 0.5541
sh2_Y3_85 	0.5547, 0.5394
sh3_Y1_85 	0.5620, 0.5465
sh3_Y3_85 	0.5438, 0.5284
sh4_Y1_85 	0.5657, 0.5351
sh4_Y3_85 	0.5730, 0.5396
sh5_Y1_85 	0.5620, 0.5327
sh5_Y3_85 	0.5657, 0.5344
sh6_Y1_85 	0.5985, 0.5687
sh6_Y3_85 	0.5949, 0.5709
sh7_Y1_85 	0.6131, 0.5795
sh7_Y3_85 	0.5912, 0.5568
sh8_Y1_85 	0.6241, 0.5803
sh8_Y3_85 	0.6058, 0.5672
sh9_Y1_85 	0.6168, 0.5680
sh9_Y3_85 	0.5766, 0.5282
sh10_Y1_85 	0.6715, 0.6245
sh10_Y3_85 	0.6058, 0.5553
sh1_Y1_90 	0.5292, 0.5218
sh1_Y3_90 	0.5182, 0.5076
sh2_Y1_90 	0.5693, 0.5498
sh2_Y3_90 	0.5365, 0.5236
sh3_Y1_90 	0.5474, 0.5317
sh3_Y3_90 	0.5365, 0.5210
sh4_Y1_90 	0.5547, 0.5213
sh4_Y3_90 	0.5584, 0.5306
sh5_Y1_90 	0.5730, 0.5463
sh5_Y3_90 	0.5547, 0.5237
sh6_Y1_90 	0.5949, 0.5656
sh6_Y3_90 	0.5730, 0.5417
sh7_Y1_90 	0.6131, 0.5795
sh7_Y3_90 	0.5547, 0.4919
sh8_Y1_90 	0.6204, 0.5756
sh8_Y3_90 	0.5292, 0.4751
sh9_Y1_90 	0.6131, 0.5613
sh9_Y3_90 	0.5547, 0.4825
sh10_Y1_90 	0.6715, 0.6267
sh10_Y3_90 	0.5803, 0.4811
sh1_Y1_95 	0.5255, 0.5184
sh1_Y3_95 	0.4781, 0.4624
sh2_Y1_95 	0.5766, 0.5596
sh2_Y3_95 	0.5292, 0.4852
sh3_Y1_95 	0.5328, 0.5143
sh3_Y3_95 	0.5584, 0.5277
sh4_Y1_95 	0.5620, 0.5305
sh4_Y3_95 	0.5584, 0.4963
sh5_Y1_95 	0.5730, 0.5448
sh5_Y3_95 	0.5620, 0.5126
sh6_Y1_95 	0.5985, 0.5660
sh6_Y3_95 	0.5547, 0.5156
sh7_Y1_95 	0.6095, 0.5750
sh7_Y3_95 	0.5109, 0.4493
sh8_Y1_95 	0.6314, 0.5897
sh8_Y3_95 	0.5292, 0.4768
sh9_Y1_95 	0.6131, 0.5613
sh9_Y3_95 	0.5474, 0.4804
sh10_Y1_95 	0.6606, 0.6069
sh10_Y3_95 	0.5584, 0.4686
sh1_Y1_100 	0.5255, 0.5184
sh1_Y3_100 	0.4818, 0.4667
sh2_Y1_100 	0.5657, 0.5466
sh2_Y3_100 	0.5365, 0.4858
sh3_Y1_100 	0.5584, 0.5432
sh3_Y3_100 	0.5584, 0.5190
sh4_Y1_100 	0.5511, 0.5167
sh4_Y3_100 	0.5839, 0.5175
sh5_Y1_100 	0.5657, 0.5387
sh5_Y3_100 	0.5365, 0.4883
sh6_Y1_100 	0.5912, 0.5611
sh6_Y3_100 	0.5584, 0.5015
sh7_Y1_100 	0.6022, 0.5629
sh7_Y3_100 	0.5657, 0.4950
sh8_Y1_100 	0.6277, 0.5850
sh8_Y3_100 	0.5401, 0.4823
sh9_Y1_100 	0.6241, 0.5757
sh9_Y3_100 	0.5474, 0.4766
sh10_Y1_100 	0.6642, 0.6098
sh10_Y3_100 	0.5766, 0.4896
sh1_Y1_105 	0.5255, 0.5184
sh1_Y3_105 	0.4964, 0.4775
sh2_Y1_105 	0.5657, 0.5466
sh2_Y3_105 	0.5620, 0.5057
sh3_Y1_105 	0.5584, 0.5432
sh3_Y3_105 	0.5438, 0.5025
sh4_Y1_105 	0.5584, 0.5275
sh4_Y3_105 	0.5693, 0.4945
sh5_Y1_105 	0.5657, 0.5401
sh5_Y3_105 	0.5803, 0.5136
sh6_Y1_105 	0.5839, 0.5523
sh6_Y3_105 	0.5620, 0.4967
sh7_Y1_105 	0.6131, 0.5766
sh7_Y3_105 	0.5620, 0.4875
sh8_Y1_105 	0.6168, 0.5709
sh8_Y3_105 	0.5693, 0.4869
sh9_Y1_105 	0.5985, 0.5439
sh9_Y3_105 	0.5876, 0.4959
sh10_Y1_105 	0.6569, 0.5995
sh10_Y3_105 	0.5985, 0.4998
sh1_Y1_110 	0.5255, 0.5184
sh1_Y3_110 	0.5109, 0.4828
sh2_Y1_110 	0.5693, 0.5510
sh2_Y3_110 	0.5620, 0.4873
sh3_Y1_110 	0.5438, 0.5267
sh3_Y3_110 	0.5657, 0.5195
sh4_Y1_110 	0.5620, 0.5336
sh4_Y3_110 	0.5803, 0.4974
sh5_Y1_110 	0.5657, 0.5387
sh5_Y3_110 	0.5803, 0.5035
sh6_Y1_110 	0.5839, 0.5549
sh6_Y3_110 	0.5766, 0.5065
sh7_Y1_110 	0.6168, 0.5811
sh7_Y3_110 	0.5657, 0.4875
sh8_Y1_110 	0.6314, 0.5897
sh8_Y3_110 	0.5803, 0.4906
sh9_Y1_110 	0.6241, 0.5813
sh9_Y3_110 	0.5912, 0.4970
sh10_Y1_110 	0.6642, 0.6165
sh10_Y3_110 	0.6095, 0.4970
sh1_Y1_115 	0.5292, 0.5222
sh1_Y3_115 	0.5036, 0.4789
sh2_Y1_115 	0.5693, 0.5510
sh2_Y3_115 	0.5584, 0.4922
sh3_Y1_115 	0.5401, 0.5226
sh3_Y3_115 	0.5657, 0.5195
sh4_Y1_115 	0.5620, 0.5321
sh4_Y3_115 	0.5876, 0.5050
sh5_Y1_115 	0.5657, 0.5387
sh5_Y3_115 	0.5803, 0.5021
sh6_Y1_115 	0.5949, 0.5656
sh6_Y3_115 	0.5803, 0.5096
sh7_Y1_115 	0.6131, 0.5766
sh7_Y3_115 	0.5766, 0.4967
sh8_Y1_115 	0.6241, 0.5838
sh8_Y3_115 	0.5876, 0.4966
sh9_Y1_115 	0.6204, 0.5765
sh9_Y3_115 	0.5949, 0.4999
sh10_Y1_115 	0.6715, 0.6222
sh10_Y3_115 	0.6204, 0.5056
sh1_Y1_120 	0.5292, 0.5222
sh1_Y3_120 	0.5000, 0.4754
sh2_Y1_120 	0.5693, 0.5498
sh2_Y3_120 	0.5511, 0.4859
sh3_Y1_120 	0.5365, 0.5184
sh3_Y3_120 	0.5547, 0.5080
sh4_Y1_120 	0.5620, 0.5289
sh4_Y3_120 	0.5912, 0.5080
sh5_Y1_120 	0.5657, 0.5387
sh5_Y3_120 	0.5876, 0.5111
sh6_Y1_120 	0.5985, 0.5687
sh6_Y3_120 	0.5803, 0.5096
sh7_Y1_120 	0.6131, 0.5766
sh7_Y3_120 	0.5766, 0.4967
sh8_Y1_120 	0.6314, 0.5897
sh8_Y3_120 	0.5912, 0.4996
sh9_Y1_120 	0.6277, 0.5843
sh9_Y3_120 	0.6058, 0.5088
sh10_Y1_120 	0.6569, 0.6086
sh10_Y3_120 	0.6204, 0.5056

# 내 방식대로!

In [92]:
sp500 = sp500.dropna()

In [94]:
sp500 = sp500.loc['2001-07-01':]

In [95]:
sp500.head()

,Open,High,Low,Close,Volume,pct_change,close_ma_3,close_ma_5,close_ma_7,close_ma_9,...,sh8_Y1_120,sh8_Y3_120,Y1_120_s9,Y3_120_s9,sh9_Y1_120,sh9_Y3_120,Y1_120_s10,Y3_120_s10,sh10_Y1_120,sh10_Y3_120
Date,,,,,,,,,,,,,,,,,,,,,
2001-07-02,1224.420044,1239.780029,1224.030029,1236.719971,1.12830,0.010079,1229.099976,1223.025977,1222.725691,1224.362210,...,-35.000863,-8.496583,-20.822115,-6.861168,-48.230966,-9.812834,-21.677198,-7.716252,-36.240976,-11.061668
2001-07-03,1236.709961,1236.709961,1229.430054,1234.449951,0.62211,-0.001836,1231.849976,1226.563965,1224.025687,1225.618869,...,-47.574132,-9.156000,-22.210635,-6.636502,-35.584142,-10.404834,-23.092135,-7.518002,-42.314122,-11.653168
2001-07-05,1234.449951,1234.449951,1219.150024,1219.239990,0.93490,-0.012321,1230.136637,1228.197974,1224.117118,1223.641086,...,-34.687643,-9.508334,-36.610763,-6.723169,-41.417623,-10.756668,-37.420596,-7.533002,-34.107564,-11.922751
2001-07-06,1219.239990,1219.239990,1188.739990,1190.589966,1.05670,-0.023498,1214.759969,1221.075977,1220.378540,1219.778863,...,-40.351289,-9.690334,-64.469703,-6.998419,-33.041230,-10.856417,-65.260787,-7.789503,-37.211274,-12.134084
2001-07-09,1190.589966,1201.760010,1189.750000,1198.780029,1.04570,0.006879,1202.869995,1215.955981,1218.622838,1217.576647,...,-31.975647,-9.790834,-55.740723,-7.525085,-36.145691,-11.068501,-56.279640,-8.064002,-55.965638,-12.591000

In [96]:
def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset) - look_back - 1):
        a = dataset[i:(i+look_back)]
        dataX.append(a)
        dataY.append(dataset[i+look_back])
    return np.array(dataX), np.array(dataY)

In [139]:
train, test = train_test_split(sp500, 0.9, dtrain=True)

In [141]:
# create dataset for learning
look_back = 100
trainX, trainY = create_dataset(train[X].values, look_back)
testX, testY = create_dataset(test[X].values, look_back)

trainY = train[y_li].iloc[look_back:-1].values
testY = test[y_li].iloc[look_back:-1].values

In [142]:
trainX.shape, trainY.shape

((3836, 100, 56), (3836, 540))

In [143]:
testX.shape, testY.shape

((337, 100, 56), (337, 540))

In [144]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
import math
from sklearn.metrics import mean_squared_error

Using TensorFlow backend.

In [148]:
trainY[:,0]

array([11.679931, -0.75    , -9.549927, ..., -2.559815,  0.989991,
        3.530029])

In [150]:
# simple lstm network learning
model = Sequential()
model.add(LSTM(4, input_shape=(look_back, len(X))))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY[:,0], epochs=100, batch_size=1, verbose=2)

Epoch 1/100

KeyboardInterrupt:

In [ ]:
# make prediction
testPredict = model.predict(testX)
testScore = math.sqrt(mean_squared_error(testY[:,0], testPredict))
print('Train Score: {:.2f} RMSE'.format(testScore))