In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# KOSPI200 불러오기 & 데이터셋 생성

In [4]:
import pickle
with open('raw_data_20180811.pickle','rb') as handle:

    raw_data = pickle.load(handle)
    
kospi200 = pd.read_excel("C:\\Users\\axasd\\Downloads\\상장법인목록.xlsx")
kospi200 = kospi200[kospi200.columns[:2]]
kospi200["종목코드"] = kospi200["종목코드"].map('{:06d}'.format)

code_dict = {
    i : j for i, j in zip(kospi200["회사명"], kospi200["종목코드"])
}

In [5]:
for i in raw_data.keys():
    raw_data[i] = raw_data[i].assign(sum_close_5 = raw_data[i].Close.rolling(window =5).sum())
    raw_data[i] = raw_data[i].assign(sum_close_7 = raw_data[i].Close.rolling(window =7).sum())
    raw_data[i] = raw_data[i].assign(sum_close_9 = raw_data[i].Close.rolling(window =9).sum())
    raw_data[i] = raw_data[i].assign(ma_3 = raw_data[i].Close.rolling(window = 3).mean())
    raw_data[i] = raw_data[i].assign(ma_5 = raw_data[i].Close.rolling(window = 5).mean())
    raw_data[i] = raw_data[i].assign(ma_10 = raw_data[i].Close.rolling(window = 10).mean())
    raw_data[i] = raw_data[i].assign(ma_15 = raw_data[i].Close.rolling(window = 15).mean())

for i in raw_data.keys():
    raw_data[i] = raw_data[i].assign(pct_change5 = raw_data[i].sum_close_5.pct_change().fillna(0))
    raw_data[i] = raw_data[i].assign(pct_change7 = raw_data[i].sum_close_7.pct_change().fillna(0))
    raw_data[i] = raw_data[i].assign(pct_change9 = raw_data[i].sum_close_9.pct_change().fillna(0))
    raw_data[i] = raw_data[i].assign(sum_5_Y = np.where(raw_data[i]["pct_change5"].fillna(0)>=0, 1,0))
    raw_data[i] = raw_data[i].assign(sum_7_Y = np.where(raw_data[i]["pct_change7"].fillna(0)>=0, 1,0))
    raw_data[i] = raw_data[i].assign(sum_9_Y = np.where(raw_data[i]["pct_change9"].fillna(0)>=0, 1,0))
    
for i in raw_data.keys():
    raw_data[i] = raw_data[i].dropna(axis=0)

In [6]:
copy_keys = kospi200["종목코드"]
for i in copy_keys:
    if (len(raw_data[i]) < 252):
        del raw_data[i]

In [7]:
kospi200["종목코드"][2]

'282330'

In [8]:
raw_data["006840"]

,Open,High,Low,Close,Adj Close,Volume,sum_close_5,sum_close_7,sum_close_9,ma_3,ma_5,ma_10,ma_15,pct_change5,pct_change7,pct_change9,sum_5_Y,sum_7_Y,sum_9_Y
Date,,,,,,,,,,,,,,,,,,,
2012-01-20,14128.200195,14128.200195,13620.799805,13855.000000,13250.137695,153356,68670.000000,96594.599609,124382.599609,13855.000000,13734.000000,13884.250000,14250.460026,-0.003115,0.000809,-0.004840,0,1,0
2012-01-25,14011.099609,14011.099609,13659.799805,13855.000000,13250.137695,120580,68884.700195,96594.599609,124226.500000,13907.033203,13776.940039,13823.759961,14185.413346,0.003127,0.000000,-0.001255,1,1,0
2012-01-26,13894.000000,14108.700195,13894.000000,14011.099609,13399.422852,85933,69431.099609,96536.099609,124460.699218,13907.033203,13886.219922,13823.759961,14096.953320,0.007932,-0.000606,0.001885,1,0,1
2012-01-27,14011.099609,14011.099609,13737.900391,13855.000000,13250.137695,119775,69587.199218,96750.799804,124460.699218,13907.033203,13917.439844,13831.569922,14001.986654,0.002248,0.002224,0.000000,1,1,1
2012-01-30,13913.500000,13972.099609,13484.200195,13503.700195,12914.173828,144388,69079.799804,96789.799804,123894.799804,13789.933268,13815.959961,13796.439941,13899.213346,-0.007292,0.000403,-0.004547,0,1,0
2012-01-31,13581.799805,13933.000000,13425.700195,13894.000000,13287.435547,151990,69118.799804,96984.899413,124148.499999,13750.900065,13823.759961,13778.879980,13864.086654,0.000565,0.002016,0.002048,1,1,1
2012-02-01,14011.099609,14284.299805,13894.000000,14011.099609,13399.422852,206438,69274.899413,96984.899413,124694.899413,13802.933268,13854.979883,13815.959961,13834.166601,0.002258,0.000000,0.004401,1,1,1
2012-02-02,14225.700195,14498.900391,14167.200195,14284.299805,13660.697266,191139,69548.099609,97414.199218,125280.298827,14063.133138,13909.619922,13897.919922,13852.379948,0.003944,0.004426,0.004695,1,1,1
2012-02-03,14420.900391,14420.900391,13952.599609,14069.599609,13455.370117,104338,69762.699218,97628.798827,125338.798827,14121.666341,13952.539844,13934.989844,13871.893229,0.003086,0.002203,0.000467,1,1,1
2012-02-06,14225.700195,14245.299805,13718.400391,13796.400391,13194.096680,131720,70055.399414,97414.099609,125280.199218,14050.099935,14011.079883,13913.519922,13867.986588,0.004196,-0.002199,-0.000468,1,0,0
2012-02-07,13855.000000,13894.000000,13581.799805,13718.400391,13119.502930,138797,69879.799805,97277.500000,125143.599609,13861.466797,13975.959961,13899.859961,13844.573307,-0.002507,-0.001402,-0.001090,0,0,0
2012-02-08,13776.900391,14616.000000,13640.299805,14616.000000,13977.915039,358544,70484.700196,98389.799805,125748.500000,14043.600261,14096.940039,13975.959961,13909.619987,0.008656,0.011434,0.004834,1,1,1
2012-02-09,14830.700195,14850.200195,14401.400391,14674.599609,14033.958008,222196,70875.000000,99170.399414,126568.099609,14336.333333,14175.000000,14042.309961,13990.279948,0.005537,0.007934,0.006518,1,1,1
2012-02-10,14830.700195,14889.200195,14284.299805,14303.799805,13679.345703,166910,71109.200196,99463.099610,127368.199219,14531.466471,14221.840039,14087.189941,14030.606575,0.003304,0.002951,0.006321,1,1,1
2012-02-13,14440.400391,14772.099609,14362.299805,14733.099609,14089.904297,190606,72045.899414,99911.899414,128207.298828,14570.499674,14409.179883,14210.129883,14078.739909,0.013173,0.004512,0.006588,1,1,1
2012-02-14,14889.200195,14889.200195,14498.900391,14733.099609,14089.904297,109065,73060.598632,100575.399414,128929.298828,14589.999674,14612.119726,14294.039844,14137.279883,0.014084,0.006641,0.005632,1,1,1
2012-02-15,14830.700195,14830.700195,14420.900391,14635.500000,13996.563477,155544,73080.098632,101414.499023,129280.499023,14700.566406,14616.019726,14356.479883,14189.313216,0.000267,0.008343,0.002724,1,1,1
2012-02-16,14557.500000,14752.599609,14264.799805,14401.400391,13772.685547,157684,72806.899414,102097.499023,129612.299805,14590.000000,14561.379883,14368.189941,14215.333268,-0.003738,0.006735,0.002567,0,1,1
2012-02-17,14498.900391,14596.500000,14245.299805,14284.299805,13660.697266,110838,72787.399414,101765.798828,130100.199219,14440.400065,14557.479883,14389.659961,14243.953255,-0.000268,-0.003249,0.003764,0,0,1
2012-02-20,14459.900391,14557.500000,13991.599609,13991.599609,13380.775391,224674,72045.899414,101082.798828,130373.398437,14225.766602,14409.179883,14409.179883,14276.479883,-0.010187,-0.006711,0.002100,0,0,1
2012-02-21,14069.599609,14108.700195,13328.099609,13620.799805,13026.163086,441915,70933.599610,100399.798828,129378.198242,13965.566406,14186.719922,14399.419824,14258.266536,-0.015439,-0.006757,-0.007633,0,0,0
2012-02-22,13620.799805,13620.799805,13211.000000,13503.700195,12914.173828,291088,69801.799805,99170.399414,128207.298828,13705.366536,13960.359961,14288.189844,14224.439909,-0.015956,-0.012245,-0.009050,0,0,0
2012-02-23,13484.200195,13679.400391,13269.599609,13523.200195,12932.823242,159147,68923.599609,97960.500000,127426.699218,13549.233398,13784.719922,14173.049902,14173.699935,-0.012581,-0.012200,-0.006089,0,0,0
2012-02-24,13367.099609,13913.500000,13367.099609,13679.400391,13082.205078,159119,68318.700195,97004.400391,126373.000000,13568.766927,13663.740039,14110.609961,14147.686654,-0.008776,-0.009760,-0.008269,0,0,0
2012-02-27,13679.400391,13679.400391,13191.500000,13211.000000,12634.252930,129911,67538.100586,95814.000000,124850.900391,13471.200195,13507.620117,13958.400000,14108.659961,-0.011426,-0.012272,-0.012045,0,0,0
2012-02-28,13211.000000,13347.599609,12957.299805,13347.599609,12764.889648,134908,67264.900390,94877.299804,123563.000000,13412.666667,13452.980078,13819.850000,14083.939909,-0.004045,-0.009776,-0.010316,0,0,0
2012-02-29,13523.200195,13581.799805,13328.099609,13581.799805,12988.866211,98575,67343.000000,94467.500000,122743.399414,13380.133138,13468.600000,13714.479980,14014.993229,0.001161,-0.004319,-0.006633,1,0,0
2012-03-02,13659.799805,13718.400391,13503.700195,13679.400391,13082.205078,85989,67499.200196,94526.100586,122138.500000,13536.266602,13499.840039,13642.279980,13948.646615,0.002319,0.000620,-0.004928,1,1,0
2012-03-05,13757.400391,13757.400391,13425.700195,13464.700195,12876.877930,72896,67284.500000,94487.100586,121611.600586,13575.300130,13456.900000,13560.320020,13892.706641,-0.003181,-0.000413,-0.004314,0,0,0
2012-03-06,13386.599609,13406.200195,13093.900391,13191.500000,12615.606445,138323,67265.000000,94155.400391,121182.300781,13445.200195,13453.000000,13480.310059,13789.933333,-0.000290,-0.003511,-0.003530,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-06-21,77600.000000,80800.000000,77600.000000,79000.000000,79000.000000,28089,398800.000000,571200.000000,737300.000000,78766.666667,79760.000000,81790.000000,81113.333333,-0.018459,-0.008850,-0.002165,0,0,0
2018-06-22,79000.000000,79400.000000,74700.000000,76500.000000,76500.000000,47003,392000.000000,561800.000000,731800.000000,78400.000000,78400.000000,81380.000000,81040.000000,-0.017051,-0.016457,-0.007460,0,0,0
2018-06-25,76600.000000,76600.000000,73800.000000,75500.000000,75500.000000,46648,388300.000000,550800.000000,723200.000000,77000.000000,77660.000000,80730.000000,80706.666667,-0.009439,-0.019580,-0.011752,0,0,0
2018-06-26,75000.000000,77000.000000,74200.000000,76200.000000,76200.000000,28302,386900.000000,543700.000000,713500.000000,76066.666667,77380.000000,79940.000000,80406.666667,-0.003605,-0.012890,-0.013413,0,0,0
2018-06-27,75500.000000,76500.000000,74500.000000,74900.000000,74900.000000,20044,382100.000000,539400.000000,701900.000000,75533.333333,76420.000000,78840.000000,80066.666667,-0.012406,-0.007909,-0.016258,0,0,0
2018-06-28,75300.000000,75800.000000,74300.000000,75300.000000,75300.000000,23333,378400.000000,537100.000000,693900.000000,75466.666667,75680.000000,77720.000000,79753.333333,-0.009683,-0.004264,-0.011398,0,0,0
2018-06-29,75300.000000,75700.000000,73000.000000,75400.000000,75400.000000,35679,377300.000000,532800.000000,690100.000000,75200.000000,75460.000000,76930.000000,79406.666667,-0.002907,-0.008006,-0.005476,0,0,0
2018-07-02,75600.000000,75600.000000,70000.000000,70200.000000,70200.000000,30648,372000.000000,524000.000000,682700.000000,73633.333333,74400.000000,76030.000000,78620.000000,-0.014047,-0.016517,-0.010723,0,0,0
2018-07-03,70800.000000,72000.000000,70100.000000,70100.000000,70100.000000,20061,365900.000000,517600.000000,673100.000000,71900.000000,73180.000000,75280.000000,77686.666667,-0.016398,-0.012214,-0.014062,0,0,0
2018-07-04,69400.000000,71000.000000,69200.000000,70600.000000,70600.000000,12504,361600.000000,512700.000000,664700.000000,70300.000000,72320.000000,74370.000000,76666.666667,-0.011752,-0.009467,-0.012480,0,0,0
2018-07-05,70300.000000,71400.000000,70300.000000,71000.000000,71000.000000,7463,357300.000000,507500.000000,659200.000000,70566.666667,71460.000000,73570.000000,75633.333333,-0.011892,-0.010142,-0.008274,0,0,0
2018-07-06,71000.000000,73000.000000,71000.000000,73000.000000,73000.000000,13078,354900.000000,505600.000000,656700.000000,71533.333333,70980.000000,73220.000000,74946.666667,-0.006717,-0.003744,-0.003792,0,0,0
2018-07-09,72500.000000,73200.000000,70800.000000,72900.000000,72900.000000,15931,357600.000000,503200.000000,653400.000000,72300.000000,71520.000000,72960.000000,74526.666667,0.007608,-0.004747,-0.005025,1,0,0
2018-07-10,72900.000000,75500.000000,72900.000000,74400.000000,74400.000000,21384,361900.000000,502200.000000,652900.000000,73433.333333,72380.000000,72780.000000,74313.333333,0.012025,-0.001987,-0.000765,1,0,0
2018-07-11,74000.000000,74600.000000,72400.000000,73200.000000,73200.000000,20576,364500.000000,505200.000000,650800.000000,73500.000000,72900.000000,72610.000000,73880.000000,0.007184,0.005974,-0.003216,1,1,0
2018-07-12,74000.000000,75800.000000,73300.000000,75000.000000,75000.000000,13608,368500.000000,510100.000000,650400.000000,74200.000000,73700.000000,72580.000000,73613.333333,0.010974,0.009699,-0.000615,1,1,0
2018-07-13,75500.000000,77700.000000,75500.000000,77700.000000,77700.000000,27561,373200.000000,517200.000000,657900.000000,75300.000000,74640.000000,72810.000000,73693.333333,0.012754,0.013919,0.011531,1,1,1
2018-07-16,77900.000000,79400.000000,77200.000000,79000.000000,79000.000000,28693,379300.000000,525200.000000,666800.000000,77233.333333,75860.000000,73690.000000,73926.666667,0.016345,0.015468,0.013528,1,1,1
2018-07-17,79300.000000,80400.000000,78200.000000,80300.000000,80300.000000,32998,385200.000000,532500.000000,676500.000000,79000.000000,77040.000000,74710.000000,74200.000000,0.015555,0.013899,0.014547,1,1,1
2018-07-18,80100.000000,80100.000000,77400.000000,78300.000000,78300.000000,15978,390300.000000,537900.000000,683800.000000,79200.000000,78060.000000,75480.000000,74426.666667,0.013240,0.010141,0.010791,1,1,1
2018-07-19,78100.000000,78100.000000,75100.000000,75800.000000,75800.000000,23643,391100.000000,539300.000000,686600.000000,78133.333333,78220.000000,75960.000000,74460.000000,0.002050,0.002603,0.004095,1,1,1
2018-07-20,75700.000000,77100.000000,75200.000000,76400.000000,76400.000000,13026,389800.000000,542500.000000,690100.000000,76833.333333,77960.000000,76300.000000,74526.666667,-0.003324,0.005934,0.005098,0,1,1
2018-07-23,77000.000000,77000.000000,74300.000000,74900.000000,74900.000000,20821,385700.000000,542400.000000,690600.000000,75700.000000,77140.000000,76500.000000,74840.000000,-0.010518,-0.000184,0.000725,0,0,1
2018-07-24,75400.000000,76400.000000,73300.000000,75800.000000,75800.000000,19684,381200.000000,540500.000000,693200.000000,75700.000000,76240.000000,76640.000000,75220.000000,-0.011667,-0.003503,0.003765,0,0,1
2018-07-25,76700.000000,79800.000000,75700.000000,76500.000000,76500.000000,32287,379400.000000,538000.000000,694700.000000,75733.333333,75880.000000,76970.000000,75613.333333,-0.004722,-0.004625,0.002164,0,0,1
2018-07-26,77900.000000,78500.000000,76800.000000,78200.000000,78200.000000,18208,381800.000000,535900.000000,695200.000000,76833.333333,76360.000000,77290.000000,76093.333333,0.006326,-0.003903,0.000720,1,0,1
2018-07-27,78800.000000,78800.000000,76800.000000,77600.000000,77600.000000,15994,383000.000000,535200.000000,693800.000000,77433.333333,76600.000000,77280.000000,76400.000000,0.003143,-0.001306,-0.002014,1,0,0
2018-07-30,77000.000000,77200.000000,75200.000000,75600.000000,75600.000000,20158,383700.000000,535000.000000,689100.000000,77133.333333,76740.000000,76940.000000,76580.000000,0.001828,-0.000374,-0.006774,1,0,0
2018-07-31,75600.000000,78200.000000,75100.000000,77200.000000,77200.000000,26955,385100.000000,535800.000000,688000.000000,76800.000000,77020.000000,76630.000000,76766.666667,0.003649,0.001495,-0.001596,1,1,0
2018-08-01,77300.000000,78400.000000,76600.000000,77100.000000,77100.000000,20362,385700.000000,538000.000000,689300.000000,76633.333333,77140.000000,76510.000000,77026.666667,0.001558,0.004106,0.001890,1,1,1

### Train, Test Split

In [9]:
train1 = {}
train_idx1 = {}
test1 = {}
test_idx1 = {}
for code, df in raw_data.items():
    train1[code] = df.iloc[:int(len(df)*0.8)][["Open","ma_5", "ma_10"]]
    train_idx1[code] = df.iloc[:int(len(df)*0.8)]["sum_9_Y"]
    test1[code] = df.iloc[int(len(df)*0.8):][["Open","ma_5", "ma_10"]]
    test_idx1[code] = df.iloc[int(len(df)*0.8):]["sum_9_Y"]

In [10]:
train2 = {}
train_idx2 = {}
test2 = {}
test_idx2 = {}
for code, df in raw_data.items():
    train2[code] = df.iloc[:int(len(df)*0.8)][["Open","ma_5", "ma_15"]]
    train_idx2[code] = df.iloc[:int(len(df)*0.8)]["sum_9_Y"]
    test2[code] = df.iloc[int(len(df)*0.8):][["Open","ma_5", "ma_15"]]
    test_idx2[code] = df.iloc[int(len(df)*0.8):]["sum_9_Y"]

In [11]:
train3 = {}
train_idx3 = {}
test3 = {}
test_idx3 = {}
for code, df in raw_data.items():
    train3[code] = df.iloc[:int(len(df)*0.8)][["Open","ma_10", "ma_15"]]
    train_idx3[code] = df.iloc[:int(len(df)*0.8)]["sum_9_Y"]
    test3[code] = df.iloc[int(len(df)*0.8):][["Open","ma_10", "ma_15"]]
    test_idx3[code] = df.iloc[int(len(df)*0.8):]["sum_9_Y"]

In [12]:
train4 = {}
train_idx4 = {}
test4 = {}
test_idx4 = {}
for code, df in raw_data.items():
    train4[code] = df.iloc[:int(len(df)*0.8)][["Open","ma_5", "ma_10","ma_15"]]
    train_idx4[code] = df.iloc[:int(len(df)*0.8)]["sum_9_Y"]
    test4[code] = df.iloc[int(len(df)*0.8):][["Open","ma_5", "ma_10","ma_15"]]
    test_idx4[code] = df.iloc[int(len(df)*0.8):]["sum_9_Y"]

In [13]:
train5 = {}
train_idx5 = {}
test5 = {}
test_idx5 = {}
for code, df in raw_data.items():
    train5[code] = df.iloc[:int(len(df)*0.8)][["Open","Volume","ma_5", "ma_10","ma_15"]]
    train_idx5[code] = df.iloc[:int(len(df)*0.8)]["sum_9_Y"]
    test5[code] = df.iloc[int(len(df)*0.8):][["Open","Volume","ma_5", "ma_10","ma_15"]]
    test_idx5[code] = df.iloc[int(len(df)*0.8):]["sum_9_Y"]

In [14]:
train6 = {}
train_idx6 = {}
test6 = {}
test_idx6 = {}
for code, df in raw_data.items():
    train6[code] = df.iloc[:int(len(df)*0.8)][["Open","ma_3","ma_5", "ma_10"]]
    train_idx6[code] = df.iloc[:int(len(df)*0.8)]["sum_9_Y"]
    test6[code] = df.iloc[int(len(df)*0.8):][["Open","ma_3","ma_5", "ma_10"]]
    test_idx6[code] = df.iloc[int(len(df)*0.8):]["sum_9_Y"]

### Scale 조정

In [15]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
li1 = ["Open","ma_5", "ma_10"]
for code in raw_data.keys():
    train1[code][li1] = std_scaler.fit_transform(train1[code][li1].values)
    test1[code][li1] = std_scaler.fit_transform(test1[code][li1].values)

In [16]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
li2 = ["Open","ma_5", "ma_15"]
for code in raw_data.keys():
    train2[code][li2] = std_scaler.fit_transform(train2[code][li2].values)
    test2[code][li2] = std_scaler.fit_transform(test2[code][li2].values)

In [17]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
li3 = ["Open","ma_10", "ma_15"]
for code in raw_data.keys():
    train3[code][li3] = std_scaler.fit_transform(train3[code][li3].values)
    test3[code][li3] = std_scaler.fit_transform(test3[code][li3].values)

In [18]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
li4 = ["Open","ma_5", "ma_10","ma_15"]
for code in raw_data.keys():
    train4[code][li4] = std_scaler.fit_transform(train4[code][li4].values)
    test4[code][li4] = std_scaler.fit_transform(test4[code][li4].values)

In [19]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
li5 = ["Open","Volume","ma_5", "ma_10","ma_15"]
for code in raw_data.keys():
    train5[code][li5] = std_scaler.fit_transform(train5[code][li5].values)
    test5[code][li5] = std_scaler.fit_transform(test5[code][li5].values)

In [20]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
li6 = ["Open","ma_3","ma_5", "ma_10"]
for code in raw_data.keys():
    train6[code][li6] = std_scaler.fit_transform(train6[code][li6].values)
    test6[code][li6] = std_scaler.fit_transform(test6[code][li6].values)

### model 호출

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

log_clf = LogisticRegression()
DTC_clf = DecisionTreeClassifier()
svm_clf = SVC()

### Predict

In [22]:
score_list1 = pd.DataFrame(columns=('LR','DT','SVM'))

for i in raw_data.keys():
    a1=[]
    X_train1 = train1[i].values
    y_train1 = train_idx1[i].values
    X_test1 = test1[i].values
    y_test1 = test_idx1[i].values
    for clf in (log_clf, DTC_clf, svm_clf):
        clf.fit(X_train1, y_train1)
        y_pred1 = clf.predict(X_test1)
        a1.append(accuracy_score(y_test1, y_pred1))
    score_list1.loc[i] = a1

In [23]:
score_list2 = pd.DataFrame(columns=('LR','DT','SVM'))

for i in raw_data.keys():
    a2=[]
    X_train2 = train2[i].values
    y_train2 = train_idx2[i].values
    X_test2 = test2[i].values
    y_test2 = test_idx2[i].values
    for clf in (log_clf, DTC_clf, svm_clf):
        clf.fit(X_train2, y_train2)
        y_pred2 = clf.predict(X_test2)
        a2.append(accuracy_score(y_test2, y_pred2))
    score_list2.loc[i] = a2

In [24]:
score_list3 = pd.DataFrame(columns=('LR','DT','SVM'))

for i in raw_data.keys():
    a3=[]
    X_train3 = train3[i].values
    y_train3 = train_idx3[i].values
    X_test3 = test3[i].values
    y_test3 = test_idx3[i].values
    for clf in (log_clf, DTC_clf, svm_clf):
        clf.fit(X_train3, y_train3)
        y_pred3 = clf.predict(X_test3)
        a3.append(accuracy_score(y_test3, y_pred3))
    score_list3.loc[i] = a3

In [25]:
score_list4 = pd.DataFrame(columns=('LR','DT','SVM'))

for i in raw_data.keys():
    a4=[]
    X_train4 = train4[i].values
    y_train4 = train_idx4[i].values
    X_test4 = test4[i].values
    y_test4 = test_idx4[i].values
    for clf in (log_clf, DTC_clf, svm_clf):
        clf.fit(X_train4, y_train4)
        y_pred4 = clf.predict(X_test4)
        a4.append(accuracy_score(y_test4, y_pred4))
    score_list4.loc[i] = a4

In [26]:
score_list5 = pd.DataFrame(columns=('LR','DT','SVM'))

for i in raw_data.keys():
    a5=[]
    X_train5 = train5[i].values
    y_train5 = train_idx5[i].values
    X_test5 = test5[i].values
    y_test5 = test_idx5[i].values
    for clf in (log_clf, DTC_clf, svm_clf):
        clf.fit(X_train5, y_train5)
        y_pred5 = clf.predict(X_test5)
        a5.append(accuracy_score(y_test5, y_pred5))
    score_list5.loc[i] = a5

In [27]:
from sklearn.metrics import accuracy_score

score_list6 = pd.DataFrame(columns=('LR','DT','SVM'))


for i in raw_data.keys():
    a6=[]
    X_train6 = train6[i].values
    y_train6 = train_idx6[i].values
    X_test6 = test6[i].values
    y_test6 = test_idx6[i].values
    for clf in (log_clf, DTC_clf, svm_clf):
        clf.fit(X_train6, y_train6)
        y_pred6 = clf.predict(X_test6)
        a6.append(accuracy_score(y_test6, y_pred6))
    score_list6.loc[i] = a6

In [28]:
# Y : 5일평균주가 등락 

print(score_list1.describe()) #open, ma5, ma10 // 성능이 가장 좋음
print(score_list2.describe()) #open, ma5, ma15
print(score_list3.describe()) #open, ma10, ma15
print(score_list4.describe()) # open, ma5, ma10, ma15
print(score_list5.describe()) #open, ,volume, ma5, ma10, ma15
print(score_list6.describe()) #open, ma3, ma5, ma10

               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.804962    0.742088    0.767048
std      0.054971    0.049653    0.078292
min      0.419255    0.470588    0.411765
25%      0.788820    0.717391    0.748447
50%      0.813665    0.748447    0.788820
75%      0.832298    0.779503    0.816176
max      0.897143    0.826087    0.900621
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.829972    0.756498    0.810072
std      0.044877    0.049771    0.063201
min      0.475490    0.563725    0.421569
25%      0.810559    0.726708    0.795031
50%      0.835404    0.763975    0.822981
75%      0.857143    0.795031    0.847826
max      0.913043    0.854037    0.916149
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.807930    0.740378    0.790367
std      0.051970    0.047334    0.062879
min      0.400621    0.578431    0.421569
25%      0.791925    0.714286    0.770186
50%      0.813665    0.748447    0.801242
75%      0.835404    0.771930    0.829193
max      0.897143    0.841615    0.900621
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.834615    0.756890    0.809345
std      0.044659    0.050037    0.068249
min      0.475490    0.504902    0.421569
25%      0.816770    0.726708    0.795031
50%      0.841615    0.763975    0.822981
75%      0.863354    0.791925    0.854037
max      0.906832    0.847826    0.906832
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.834248    0.736213    0.795265
std      0.045620    0.056026    0.070189
min      0.470588    0.509804    0.426471
25%      0.816770    0.704969    0.779503
50%      0.841615    0.742236    0.813665
75%      0.863354    0.776398    0.835404
max      0.909938    0.851429    0.891304
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.817415    0.753510    0.774168
std      0.054921    0.049685    0.081575
min      0.425466    0.470588    0.411765
25%      0.802721    0.729814    0.748447
50%      0.822981    0.760000    0.795031
75%      0.844720    0.785714    0.819876
max      0.902857    0.857143    0.897516

In [29]:
# Y : 7일평균주가 등락 

print(score_list1.describe()) #open, ma5, ma10
print(score_list2.describe()) #open, ma5, ma15
print(score_list3.describe()) #open, ma10, ma15
print(score_list4.describe()) # open, ma5, ma10, ma15
print(score_list5.describe()) #open, ,volume, ma5, ma10, ma15
print(score_list6.describe()) #open, ma3, ma5, ma10 // 성능이 가장 좋음

               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.804962    0.742088    0.767048
std      0.054971    0.049653    0.078292
min      0.419255    0.470588    0.411765
25%      0.788820    0.717391    0.748447
50%      0.813665    0.748447    0.788820
75%      0.832298    0.779503    0.816176
max      0.897143    0.826087    0.900621
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.829972    0.756498    0.810072
std      0.044877    0.049771    0.063201
min      0.475490    0.563725    0.421569
25%      0.810559    0.726708    0.795031
50%      0.835404    0.763975    0.822981
75%      0.857143    0.795031    0.847826
max      0.913043    0.854037    0.916149
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.807930    0.740378    0.790367
std      0.051970    0.047334    0.062879
min      0.400621    0.578431    0.421569
25%      0.791925    0.714286    0.770186
50%      0.813665    0.748447    0.801242
75%      0.835404    0.771930    0.829193
max      0.897143    0.841615    0.900621
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.834615    0.756890    0.809345
std      0.044659    0.050037    0.068249
min      0.475490    0.504902    0.421569
25%      0.816770    0.726708    0.795031
50%      0.841615    0.763975    0.822981
75%      0.863354    0.791925    0.854037
max      0.906832    0.847826    0.906832
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.834248    0.736213    0.795265
std      0.045620    0.056026    0.070189
min      0.470588    0.509804    0.426471
25%      0.816770    0.704969    0.779503
50%      0.841615    0.742236    0.813665
75%      0.863354    0.776398    0.835404
max      0.909938    0.851429    0.891304
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.817415    0.753510    0.774168
std      0.054921    0.049685    0.081575
min      0.425466    0.470588    0.411765
25%      0.802721    0.729814    0.748447
50%      0.822981    0.760000    0.795031
75%      0.844720    0.785714    0.819876
max      0.902857    0.857143    0.897516

In [30]:
# Y : 9일평균주가 등락

print(score_list1.describe()) #open, ma5, ma10
print(score_list2.describe()) #open, ma5, ma15 // SVM 성능 가장 좋음
print(score_list3.describe()) #open, ma10, ma15
print(score_list4.describe()) # open, ma5, ma10, ma15 // LR,DT 성능 가장 좋음
print(score_list5.describe()) #open, ,volume, ma5, ma10, ma15
print(score_list6.describe()) #open, ma3, ma5, ma10

               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.804962    0.742088    0.767048
std      0.054971    0.049653    0.078292
min      0.419255    0.470588    0.411765
25%      0.788820    0.717391    0.748447
50%      0.813665    0.748447    0.788820
75%      0.832298    0.779503    0.816176
max      0.897143    0.826087    0.900621
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.829972    0.756498    0.810072
std      0.044877    0.049771    0.063201
min      0.475490    0.563725    0.421569
25%      0.810559    0.726708    0.795031
50%      0.835404    0.763975    0.822981
75%      0.857143    0.795031    0.847826
max      0.913043    0.854037    0.916149
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.807930    0.740378    0.790367
std      0.051970    0.047334    0.062879
min      0.400621    0.578431    0.421569
25%      0.791925    0.714286    0.770186
50%      0.813665    0.748447    0.801242
75%      0.835404    0.771930    0.829193
max      0.897143    0.841615    0.900621
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.834615    0.756890    0.809345
std      0.044659    0.050037    0.068249
min      0.475490    0.504902    0.421569
25%      0.816770    0.726708    0.795031
50%      0.841615    0.763975    0.822981
75%      0.863354    0.791925    0.854037
max      0.906832    0.847826    0.906832
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.834248    0.736213    0.795265
std      0.045620    0.056026    0.070189
min      0.470588    0.509804    0.426471
25%      0.816770    0.704969    0.779503
50%      0.841615    0.742236    0.813665
75%      0.863354    0.776398    0.835404
max      0.909938    0.851429    0.891304
               LR          DT         SVM
count  197.000000  197.000000  197.000000
mean     0.817415    0.753510    0.774168
std      0.054921    0.049685    0.081575
min      0.425466    0.470588    0.411765
25%      0.802721    0.729814    0.748447
50%      0.822981    0.760000    0.795031
75%      0.844720    0.785714    0.819876
max      0.902857    0.857143    0.897516

## Y : 7일평균주가 등락, Y : 9일평균주가 등락 두 경우 모두 LR는 83% 였지만 DT는 77%,75% SVM의 경우 각각 79%, 81% 이 나왔다.